config/routes.rb
Conflict::Application.routes.draw do
  devise_for :users,
    controllers: {
    registrations:  "users/registrations",
    passwords:      "users/passwords",
  }

  root 'home#index'

  resources :locations do 
    collection do
      get 'import'
      post 'import_process'
      get 'download_location_template'
    end

    member do
      get 'cancel_delete'
      get 'cancel_update'
      get 'approve_delete'
      get 'approve_update'
      get 'view_difference'
      put 'apply_update_form'
    end
  end
  resources :reporters do
    collection do
      get 'getReporterCasesPagination'
      get 'export_csv'
    end
  end

  resources :alerts
  resources :settings

  resources :trends do
    collection do
      get 'fetchCaseForGraph'
      get 'download_csv'
    end
  end

  resources :messages

  resources :conflict_cases do
    collection do
      get 'get_field_options'
      get 'get_indicator_options'
      get 'export_as_kml'
      get 'export_as_shp'
      get 'failed_messages'
    end
    member do
      get 'cancel_delete'
      get 'cancel_update'
      get 'approve_delete'
      get 'approve_update'
      get 'view_difference'
      put 'apply_update_form'
    end
  end
  resources :users do
    collection do
      post 'register'

    end

    member do
      put 'update_password'
      get 'change_password'
    end
  end

  match 'messaging' => 'messaging#index', :via => :post

  

end

app/controllers/conflict_cases_controller.rb
require 'will_paginate/array'
class ConflictCasesController < ApplicationController  
  before_filter :authenticate_user!

  def index
    @fields = ConflictCase.get_fields
    @from = DateTime.strptime(params[:from], "%m-%d-%Y").to_date.to_s if params[:from]
    @to = DateTime.strptime(params[:to], "%m-%d-%Y").to_date.to_s if params[:to]
    unless @fields
      flash[:error] = "Failed to connect to resourcemap."
      @fields = []
      @conflict_cases = []
      @paging = [].paginate(:page => 1, :per_page => PageSize)
    else
      page  = params[:page]? params[:page]:1
      sites = ConflictCase.get_paging_sites_from_resource_map(PageSize, PageSize*(page.to_i - 1), @from, @to)
      @conflict_cases = ConflictCase.transform(sites["sites"], @fields)
      @paging = ([1] * sites["total"].to_i).paginate(:page => page, :per_page => PageSize)
    end
    @from = params[:from]
    @to = params[:to]
  end

  def extract_data_sources
    fields = ConflictCase.get_fields
    sites   = ConflictCase.all_from_resource_map
    conflict_cases = ConflictCase.transform(sites, fields)  
  end

  def export_file type
    date_str = DateTime.now.strftime('%Y-%m-%d %H-%M-%S')
    "conflict-#{date_str}.#{type}"
  end

  def export_dir 
    "#{Rails.root}/public/data/export/"
  end

  def export_as_kml
    file = export_file 'kml'
    kml_file = export_dir + file

    exporter = Exporter.new extract_data_sources
    exporter.to_kml_file kml_file

    send_file( kml_file, :filename      =>  file ,
                         :type          =>  'application/vnd.google-earth.kml+xml',
                         :disposition   =>  'attachment',
                         :streaming     =>  true,
                         :buffer_size   =>  '4096')
    # File.delete kml_file

  end

  def export_as_shp
    file     = export_file 'zip'
    zip_file = export_dir + file

    exporter = Exporter.new extract_data_sources
    exporter.to_sh_zip zip_file

    send_file( zip_file, :filename      =>  file ,
                         :type          =>  'application/x-gzip',
                         :disposition   =>  'attachment',
                         :streaming     =>  true,
                         :buffer_size   =>  '4096')

    # File.delete zip_file

  end

  def show
  	
  end

  def new
    @locations = Location.all
    @reporters = Reporter.all
    @fields = ConflictCase.get_fields
  	@conflict_case = ConflictCase.new()
  end

  # def create
  #   @conflict_case = ConflictCase.new(params[:conflict_case])
  #   site = @conflict_case.save_case_to_resource_map
  #   if site
  #     @conflict_case.site_id = site["id"]
  #   	if @conflict_case.save
  #       flash[:notice] = "You have successfully created conflict case #{@conflict_case.location.name}."      
  #       redirect_to conflict_cases_path
  #     else
  #       render :new
  #     end
  #   else
  #     flash[:error] = "Failed to create case on resource map application. Please try again later."
  #     render :new
  #   end
  # end

  def edit   
    conflict = ConflictCase.find(params[:id])
    if conflict.is_updated
      flash[:error] = "Case #{conflict.location.name} is already marked as updated please wait other people confirm update."
      redirect_to conflict_cases_path
    else
      @locations = Location.all
      @fields = ConflictCase.get_fields
      @conflict_case = ConflictCase.convertToConflictCase(conflict.get_conflict_from_resource_map, @fields)
    end
  end

  def update
    @conflict_case = ConflictCase.find(params[:id])
    if @conflict_case.is_updated       
      unless @conflict_case.backup.user.id == current_user.id
        flash[:error] = "Case #{@conflict_case.location.name} is already marked as updated please wait other people confirm update."
        redirect_to conflict_cases_path
      else
        flash[:error] = "Failed to update case #{@conflict_case.location.name}. Please try again later."
        redirect_to conflict_cases_path
      end

    else
      flash[:notice] = "#{@conflict_case.location.name} is marked as updated."
      conflict = params[:conflict_case]
      conflict[:properties] = params[:properties]
      Backup.create!(:entity_id => @conflict_case.id, :data => conflict.to_json, :category => ConflictCase.get_category, :user_id => current_user.id)
      @conflict_case.is_updated = true
      @conflict_case.save
      redirect_to conflict_cases_path
    end
  end

  def destroy
    @conflict_case = ConflictCase.find(params[:id])
    if @conflict_case.is_deleted 
      unless @conflict_case.backup.user.id == current_user.id
        flash[:error] = "Conflict Case is marked as deleted please click Approve to delete to confirm delete location."
        redirect_to conflict_cases_path
      else
        flash[:error] = "Failed to delete Conflict Case. Please try again later."
        redirect_to conflict_cases_path
      end
    else
      flash[:notice] = "Conflict Case is marked as deleted."
      Backup.create!(:entity_id => @conflict_case.id, :data => @conflict_case.to_json, :category => ConflictCase.get_category, :user_id => current_user.id)
      @conflict_case.is_deleted = true
      @conflict_case.save
      redirect_to conflict_cases_path
    end
  end

  def cancel_delete
    @conflict_case = ConflictCase.find(params[:id])
    if(@conflict_case.is_deleted and @conflict_case.backup)
      flash[:notice] = "#{@conflict_case.location.name} is marked as undeleted."
      @conflict_case.backup.destroy
      @conflict_case.is_deleted = false
      @conflict_case.save
      redirect_to conflict_cases_path
    else
      redirect_to conflict_cases_path
    end
  end

  def cancel_update
    @conflict_case = ConflictCase.find(params[:id])
    if(@conflict_case.is_updated and @conflict_case.backup)
      flash[:notice] = "#{@conflict_case.location.name} is marked as not updated."
      @conflict_case.backup.destroy
      @conflict_case.is_updated = false
      @conflict_case.save
      redirect_to conflict_cases_path
    else
      redirect_to conflict_cases_path
    end
  end

  def approve_delete
    @conflict_case = ConflictCase.find(params[:id])
    site = @conflict_case.destroy_case_from_resource_map
    if(@conflict_case and @conflict_case.is_deleted and @conflict_case.backup and @conflict_case.backup.user.id != current_user.id and site)
      @conflict_case.destroy!
      @conflict_case.backup.destroy!
      flash[:notice] = "You have successfully deleted #{@conflict_case.location.name}."
      redirect_to conflict_cases_path
    else
      flash[:error] = "Process delete #{@conflict_case.location.name} failed."
      redirect_to conflict_cases_path
    end
  end

  def apply_update_form
    @conflict_case = ConflictCase.find(params[:id])
    if(@conflict_case and @conflict_case.is_updated and @conflict_case.backup and @conflict_case.backup.user.id != current_user.id)
      if @conflict_case.update_to_resource_map_with_form params[:conflict_case], params[:properties]
        if(@conflict_case.update_attributes(:location_id => params["conflict_case"]["location_id"]))
          flash[:notice] = "You have successfully updated conflict case #{@conflict_case.location.name}."
          @conflict_case.backup.destroy!
          @conflict_case.is_updated = false
          @conflict_case.save
          redirect_to conflict_cases_path        
        else
          flash[:error] = "Failed to update conflict location. Please try again later."
          redirect_to conflict_cases_path
        end
      else 
        flash[:error] = "Failed to update case on resource map application. Please try again later."
        redirect_to conflict_cases_path
      end
    end
  end

  def approve_update
    @conflict_case = ConflictCase.find(params[:id])
    if(@conflict_case and @conflict_case.is_updated and @conflict_case.backup and @conflict_case.backup.user.id != current_user.id)
      if @conflict_case.update_to_resource_map
        if(@conflict_case.update_attributes(:location_id => @conflict_case.backup.data["location_id"]))
          flash[:notice] = "You have successfully updated conflict case #{@conflict_case.location.name}."
          @conflict_case.backup.destroy!
          @conflict_case.is_updated = false
          @conflict_case.save
          redirect_to conflict_cases_path
        else
          flash[:error] = "Failed to update conflict location. Please try again later."
          redirect_to conflict_cases_path
        end
      else 
        flash[:error] = "Failed to update case on resource map application. Please try again later."
        redirect_to conflict_cases_path
      end
    else
      flash[:error] = "Process update conflict failed."
      redirect_to conflict_cases_path
    end
  end

  def view_difference
    @locations = Location.all
    @fields = ConflictCase.get_fields
    conflict = ConflictCase.find(params[:id])
    @base = ConflictCase.convertToConflictCase(conflict.get_conflict_from_resource_map, @fields)
  end

  def get_field_options
    @fields = ConflictCase.get_fields
    success = false
    @fields.each do |field|
      if params[:field].to_s == field["id"].to_s
        success = true
        render :json => field["options"].to_json 
      end
    end
    unless success
      render :json => {:error => "field not found"}
    end
  end

  def get_indicator_options
    @fields = ConflictCase.get_fields
    options = []
    @fields.each do |field|
      options.push("label" => field["name"], "code" => field["code"], "id" => field["id"])
    end
    render :json => options.to_json 
  end

  def failed_messages
    messages = Message.where('is_success = false').find(:all, :order => "messages.created_at DESC")
    @messages = messages.paginate(:page => params[:page], :per_page => PageSize)
  end
end

app/views/conflict_cases/_form.html.erb
<% if conflict_case.errors.any? %>
    <div class="alert alert-block">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <div id="error_explanation">
            <h4><%= pluralize(conflict_case.errors.count, "error") %> prohibited this post from being saved:</h4>
         
            <ul>
            <% conflict_case.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    </div>
<% end %>
<%= form_for(conflict_case, :url => {action: action} , :html => {:class => 'form-horizontal'} ) do |f| %>    
    <fieldset>                
        <% @fields.each do |field| %>
            <% if field["kind"] == 'select_one' %>
                <div class="control-group">
                    <%= f.label "#{field["name"]}",:class => "control-label" %>
                    <div class="controls">
                        <select name="properties[<%= field["id"]%>]">
                            <% field["options"].each do |op| %>
                                <% if op["id"]==f.object.get_properties_value("id", field) %>
                                    <option value="<%= op["id"] %>" selected>
                                    <%= op["label"] %>
                                <% else %>
                                    <option value="<%= op["id"] %>">
                                    <%= op["label"] %>
                                <%end%>
                                </option>
                            <% end %>
                        </select>
                    </div>
                </div>
            <% end %>
        <% end %>        

        <div class="control-group">
            <%= f.label "Location",:class => "control-label" %>
            <div class="controls">
                <%= f.select(:location_id, options_for_select(@locations.collect {|p| [p.name,p.id] }, f.object.location_id)) %>
            </div>
        </div>
        
        <!-- Submit -->
        <div class="control-group">
            <div class="controls">
                <button class="btn btn-success">Save</button>
                <%=link_to "Cancel", conflict_cases_path, :class => "btn" %>
            </div>
        </div>
    </fieldset>
<% end %>

app/views/conflict_cases/_form_difference.html.erb
    <div class="row-fluid">
        <div class="span6">
            <h4> Modified</h4>
            <%= form_for(base, :url => apply_update_form_conflict_case_path(base) , :method => :put, :html => {:class => 'form-horizontal'} ) do |f| %>
                <fieldset>
                    <% @fields.each do |field| %>
                        <% if field["kind"] == 'select_one' %>
                            <div class="control-group">
                                <%= f.label "#{field["name"]}",:class => "control-label" %>
                                <div class="controls">
                                    <select name="properties[<%= field["id"]%>]">
                                        <% field["options"].each do |op| %>
                                            <% if op["id"]==get_field_value(f.object.backup.data["properties"],field, "id")  %>
                                                <option value="<%= op["id"] %>" selected>
                                                <%= op["label"] %>
                                            <% else %>
                                                <option value="<%= op["id"] %>">
                                                <%= op["label"] %>
                                            <%end%>
                                            </option>
                                        <% end %>
                                    </select>
                                </div>
                            </div>
                        <% end %>
                    <% end %>

                    <div class="control-group">
                        <%= f.label "Location",:class => "control-label" %>
                        <div class="controls">
                            <%= f.select(:location_id, options_for_select(@locations.collect {|p| [p.name,p.id] }, f.object.backup.data["location_id"])) %>
                        </div>
                    </div>   
                    
                    <!-- Submit -->
                    <div class="control-group">
                        <div class="controls">
                            <button class="btn btn-success">Approve to update</button>
                            <%=link_to "Cancel", conflict_cases_path, :class => "btn" %>
                        </div>
                    </div>
                </fieldset>
            <% end %>
        </div>
        <div class="span6">
            <h4> Original</h4>
            <%= form_for(base, :url => "#" , :method => :put, :html => {:class => 'form-horizontal'} ) do |f| %>
                <fieldset>                
                    <% @fields.each do |field| %>
                        <% if field["kind"] == 'select_one' %>
                            <div class="control-group">
                                <%= f.label "#{field["name"]}",:class => "control-label" %>
                                <div class="controls">
                                    <select name="properties[<%= field["id"]%>]">
                                        <% field["options"].each do |op| %>
                                            <% if op["id"]==f.object.get_properties_value("id",field) %>
                                                <option value="<%= op["id"] %>" selected>
                                                <%= op["label"] %>
                                            <% else %>
                                                <option value="<%= op["id"] %>">
                                                <%= op["label"] %>
                                            <%end%>
                                            </option>
                                        <% end %>
                                    </select>
                                </div>
                            </div>
                        <% end %>
                    <% end %>

                    <div class="control-group">
                        <%= f.label "Location",:class => "control-label" %>
                        <div class="controls">
                            <%= f.select(:location_id, options_for_select(@locations.collect {|p| [p.name,p.id] }, f.object.location_id)) %>
                        </div>
                    </div> 
                </fieldset>
            <% end %>
        </div>
    </div>

app/views/conflict_cases/edit.html.erb
<div class="row-fluid">
    <div id="legend">
        <legend class="">Edit Case</legend>
    </div>
    <%= render "form", {:conflict_case => @conflict_case, :action => "update" } %>
</div>

app/views/conflict_cases/failed_messages.html.erb
<div class="row-fluid">
    <div id="legend">                    
        <legend class="">Failed Messages</legend>
    </div>
</div>
<!--<table class="table table-bordered table-striped">-->
<table class="table table-condensed table-hover" id="mytable_failed_messages">
    <thead>
	    <tr>
		    <th>From</th>
		    <th>To</th>
		    <th>Original message</th>
		    <th>System reply</th>
		    <th>Date sent</th>
		    <th style="width: 36px;"></th>
	    </tr>
    </thead>
    <tbody>
	<% @messages.each do |m| %>	     
	    <tr>
	    	<td><%= m.from %></td>
	    	<td><%= m.to %></td>
	    	<td><%= m.body %></td>
	    	<td><%= m.reply %></td>
	    	<td><%= m.created_at.in_time_zone(TimeZone).strftime("%m-%d-%Y %H:%M:%S") %></td>
	    	<td>
	    	<%= link_to raw("<i class='icon-remove'></i>"), message_path(m), :method => :delete, :confirm => "Are you sure to delete this message ?" %>
	    	</td>
	   	</tr>
	<% end %>
	</tbody>
</table>
<div>
	<span class="badge" style="padding:5px;margin-right:5px;">Display record : <%= @messages.size %> / <%= @messages.total_entries %>
	</span>
</div>
<%= will_paginate @messages, renderer: BootstrapPagination::Rails %>
	    

app/views/conflict_cases/index.html.erb
<div class="btn-toolbar row-fluid">
  <div class='span8'>	
	<form action=<%= conflict_cases_path() %>  style="margin-bottom:0px;margin-top:10px;" method="GET">
	    <div class="row-fluid">
	    	<div class="span4" style="width:290px;">
	    		<div class="control-group">
	    			<label class="control-label span2" style="text-align:right;padding-right:10px;padding-top:6px;">From</label>
	    			<div class="controls">
	    				<input type="text" class="datepicker" placeholder="Start date" value="<%= @from %>" name="from">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="span4" style="width:260px;">
	    		<div class="control-group">
	    			<label class="control-label span2" style="text-align:right;padding-right:10px;padding-top:6px;">To</label>
	    			<div class="controls">
	    				<input type="text" placeholder="End date" class="datepicker" value="<%= @to %>" name="to">\
	    			</div>
	    		</div>
	    	</div>
	    	<div class="span1" style="margin-left:10px;">
	    		<button class="btn btn-info">Go</button>
	    	</div>
	    </div>	    	 
	</form>
</div>
<div class='span4'>
	<div class="btn-group pull-right btn-toolbar" >
		<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
			<i class="icon-download"></i> Export <span class="caret"></span>
		</a>
		<%
			export_params = params.slice(:from, :to)
		%>

		<ul class="dropdown-menu">
			<li><%= link_to "as KML", export_as_kml_conflict_cases_path(export_params), :title => 'Kml File version 2.1' %>
			<li><%= link_to "as Shapefile", export_as_shp_conflict_cases_path(export_params), :title => 'All related shapefiles are zipped' %></li>
		</ul>
	</div> 
	<div class="pull-right btn-toolbar" style="margin-right:10px;">
		<a class="btn" href="<%= failed_messages_conflict_cases_path %>"><i class="icon-envelope"></i> Failed Messages</a>
	</div>
</div>

</div>
<% @is_updated = false %>
<% @is_deleted = false %>

<div>
	<!--<table class="table table-bordered table-striped">-->
    <table class="table table-condensed table-hover">
	    <thead>
		    <tr>
		    	<% @fields.each do |f| %>	
			    	<th><%= f["name"] %></th>
			    <% end %>
			    <th>Location</th>
			    <th>Phone Number</th>
			    <th>Date sent</th>
			    <th style="width: 36px;"></th>
		    </tr>
	    </thead>
	    <tbody>
	    <% @conflict_cases.each do |l| %>	
	    <% class_name = "" %>
	    <% if l.is_deleted %>
	    	<% class_name = "deleted" %>
	    <% elsif l.is_updated %>
	    	<% class_name = "updated" %>
	    <% end %>			    
		    <tr class=<%= class_name %> align="right">
		    	<% @fields.each do |f| %>	
			    	<td><%= l.get_properties_value("label", f)%></td>
			    <% end %>
			    <td><%= l.location.name %>
			    <td style="width: 145px;">
					<a class="" data-toggle="modal" href="#reporterModal" onclick="showReporterInfo('<%= l.reporter.first_name %>', '<%= l.reporter.last_name %>','<%= l.reporter.sex %>','<%= l.reporter.date_of_birth %>','<%= l.reporter.cast_ethnicity %>','<%= l.reporter.phone_number %>','<%= l.reporter.address %>');"><%= l.reporter.phone_number %></a> 
				</td>
			    <td><%= l.created_at.in_time_zone(TimeZone).strftime("%m-%d-%Y %H:%M:%S") %>
			    <td class="action">
			    <% if l.is_deleted %>
			    	<% @is_deleted = true %>		    	
			    	<div class="btn-group pull-right">
			    		<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
							</i> <%= l.backup.user.first_name || "UNKNOWN" %> 
							<% if (l.backup.user.id != current_user.id and is_super_admin? current_user) or l.backup.user.id == current_user.id%>	
								<span class="caret"></span>
							<% end %>							
						</a>						
			    		<% if l.backup.user.id != current_user.id and is_super_admin? current_user%>				
							<ul class="dropdown-menu">
								<li><%= link_to " Approve to delete", approve_delete_conflict_case_path(l), :method => :get, :class => 'icon-ok-circle' %>
								<li class="divider"></li>
								<li><%= link_to " Cancel delete", cancel_delete_conflict_case_path(l), :method => :get, :class => 'icon-ban-circle' %></li>
							</ul>								
						<% elsif l.backup.user.id == current_user.id %>
							<ul class="dropdown-menu">
								<li><%= link_to " Cancel delete", cancel_delete_conflict_case_path(l), :method => :get, :class => 'icon-ban-circle' %></li>
							</ul>
						<% end %>
						
					</div>
				<% elsif l.is_updated %>
					<% @is_updated = true %>
			    	<div class="btn-group pull-right">
						<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
							<%= l.backup.user.first_name || "UNKNOWN" %>
							<% if (l.backup.user.id != current_user.id and is_super_admin? current_user) or l.backup.user.id == current_user.id%>	
									<span class="caret"></span>
							<% end %>
						</a>						
						<% if l.backup.user.id != current_user.id and is_super_admin? current_user %>	
							<ul class="dropdown-menu">
								<li><%= link_to " View the difference", view_difference_conflict_case_path(l), :method => :get, :class => 'icon-eye-open' %>
								<li class="divider"></li>
								<li><%= link_to " Approve to update", approve_update_conflict_case_path(l), :method => :get, :class => 'icon-ok-circle' %>
								<li class="divider"></li>
								<li><%= link_to " Cancel update", cancel_update_conflict_case_path(l), :method => :get, :class => 'icon-ban-circle' %></li>		
							</ul>
						<% elsif l.backup.user.id == current_user.id %>
							<ul class="dropdown-menu">
								<li><%= link_to " Cancel update", cancel_update_conflict_case_path(l), :method => :get, :class => 'icon-ban-circle' %></li>
							</ul>
						<% end %>
						</ul>
					</div>		
				<% else %>	
					<% if l.message %>
				    	<a class="" data-toggle="modal" href="#messageModal" onclick="showMessageInfo('<%= l.message.country %>','<%= l.message.channel %>','<%= l.message.from %>','<%= l.message.to %>','<%= l.message.body %>','<%= l.message.reply %>');"><i class='icon-envelope'></i></a>
				    <% end %> 					
				    <%= link_to raw("<i class='icon-pencil'></i>"), edit_conflict_case_path(l), :method => :get %>
				    <%= link_to raw("<i class='icon-remove'></i>"), conflict_case_path(l), :method => :delete, :confirm => "Are you sure to delete this case ?" %>
			    <% end %>	
			    </td>
		    </tr>
		<% end %>
		</tbody>
    </table>
</div>

<% if @is_deleted %>
	<div class="row-fluid"  style="margin:5px">
		<div class="span1 img-rounded deleted_ex">
	    	&nbsp;
	    </div>
	    <div class="span4" style="padding-top:5px">
	        Record is marked as Deleted
	    </div>
	</div>
<% end %>
<% if @is_updated %>
	<div class="row-fluid"  style="margin:5px">
		<div class="span1 img-rounded updated_ex">
	    	&nbsp;
	    </div>
	    <div class="span4" style="padding-top:5px">
	        Record is marked as Updated
	    </div>
	</div>
<% end %>
<div>
	<span class="badge" style="padding:5px;margin-right:5px;">Display record : <%= @paging.size %> / <%= @paging.total_entries %>
	</span>
</div>
<%= will_paginate @paging, renderer: BootstrapPagination::Rails %>
<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Delete Confirmation</h3>
	</div>
	<div class="modal-body">
	    <p class="error-text">Are you sure you want to delete the case?</p>
	</div>
	<div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
	    <button class="btn btn-danger" data-dismiss="modal">Delete</button>
    </div>
</div>

<div id="reporterModal" class="modal hide fade">
    <div class="modal-header">
            <button class="close" data-dismiss="modal">×</button>
            <h3> Reporter </h3>
    </div>
	<div class="modal-body" id="reporter_case">
	    <fieldset>                
	        <!-- Name -->
	        <div class="control-group">
	            <label for="reporter_First Name" style="text-align:right; padding-right:10px" class="control-label span2">First name</label>
	            <div class="controls" id="first_name">		                
	            </div>
	        </div>

	        <div class="control-group">
	            <label for="reporter_Last Name" style="text-align:right; padding-right:10px" class="control-label span2">Last name</label>
	            <div class="controls" id="last_name">
	            </div>
	        </div>

	        <div class="control-group">
	            <label for="reporter_Gender" style="text-align:right; padding-right:10px" class="control-label span2">Gender</label>
	            <div class="controls" id="gender">
	            </div>
	        </div>
	        
	        <div class="control-group">
	            <label for="reporter_Date of birth" style="text-align:right; padding-right:10px" class="control-label span2">Date of birth</label>
	            <div class="controls" id="dob">
	            </div>
	        </div>        

	        <div class="control-group">
	            <label for="reporter_Cast/Ethnicity" style="text-align:right; padding-right:10px" class="control-label span2">Cast/ethnicity</label>
	            <div class="controls" id="cast_ethnicity">
	            </div>
	        </div>

	        <div class="control-group">
	            <label for="reporter_Phone Number" style="text-align:right; padding-right:10px" class="control-label span2">Phone number</label>
	            <div class="controls"  id="phone_number">
	            </div>
	        </div>

	        <div class="control-group">
	            <label for="reporter_Address" style="text-align:right; padding-right:10px" class="control-label span2">Address</label>
	            <div class="controls" id="address">
	            </div>
	        </div>
	      
	    </fieldset>
	</div>
	<div class="modal-footer">
		<a href="#" data-dismiss="modal" class="btn btn-primary">Close</a>
	</div>
</div>


<div id="messageModal" class="modal hide fade">
    <div class="modal-header">
            <button class="close" data-dismiss="modal">×</button>
            <h3> Message detail </h3>
    </div>
	<div class="modal-body" id="reporter_case">
	    <fieldset>                
	        <!-- Name -->
	        <div class="control-group">
	            <label for="reporter_First Name" style="text-align:right; padding-right:10px" class="control-label span2">Country code</label>
	            <div class="controls" id="country">		                
	            </div>
	        </div>

	        <div class="control-group">
	            <label for="reporter_Gender" style="text-align:right; padding-right:10px" class="control-label span2">Channel</label>
	            <div class="controls" id="channel">
	            </div>
	        </div>
	        
	        <div class="control-group">
	            <label for="reporter_Date of birth" style="text-align:right; padding-right:10px" class="control-label span2">From</label>
	            <div class="controls" id="from">
	            </div>
	        </div>        

	        <div class="control-group">
	            <label for="reporter_Cast/Ethnicity" style="text-align:right; padding-right:10px" class="control-label span2">To</label>
	            <div class="controls" id="to">
	            </div>
	        </div>

	        <div class="control-group">
	            <label for="reporter_Phone Number" style="text-align:right; padding-right:10px" class="control-label span2">Original message</label>
	            <div class="controls"  id="message_text">
	            </div>
	        </div>

	        <div class="control-group">
	            <label for="reporter_Address" style="text-align:right; padding-right:10px" class="control-label span2">System reply</label>
	            <div class="controls" id="message_reply">
	            </div>
	        </div>
	      
	    </fieldset>
	</div>
	<div class="modal-footer">
		<a href="#" data-dismiss="modal" class="btn btn-primary">Close</a>
	</div>
</div>

<script>
    $('.datepicker').datepicker({format: 'mm-dd-yyyy'})
</script>

app/views/conflict_cases/new.html.erb
    <div class="row-fluid">
        <div id="legend">                    
            <legend class="">New Case</legend>
        </div>
        <!-- Name -->
        <%= render "form_new", {:conflict_case => @conflict_case, :action => "create" } %>
    </div>