config/routes.rb
Conflict::Application.routes.draw do
  devise_for :users,
    controllers: {
    registrations:  "users/registrations",
    passwords:      "users/passwords",
  }

  root 'home#index'

  resources :locations do 
    collection do
      get 'import'
      post 'import_process'
      get 'download_location_template'
    end

    member do
      get 'cancel_delete'
      get 'cancel_update'
      get 'approve_delete'
      get 'approve_update'
      get 'view_difference'
      put 'apply_update_form'
    end
  end
  resources :reporters do
    collection do
      get 'getReporterCasesPagination'
      get 'export_csv'
    end
  end

  resources :alerts
  resources :settings

  resources :trends do
    collection do
      get 'fetchCaseForGraph'
      get 'download_csv'
    end
  end

  resources :messages

  resources :conflict_cases do
    collection do
      get 'get_field_options'
      get 'get_indicator_options'
      get 'export_as_kml'
      get 'export_as_shp'
      get 'failed_messages'
    end
    member do
      get 'cancel_delete'
      get 'cancel_update'
      get 'approve_delete'
      get 'approve_update'
      get 'view_difference'
      put 'apply_update_form'
    end
  end
  resources :users do
    collection do
      post 'register'

    end

    member do
      put 'update_password'
      get 'change_password'
    end
  end

  match 'messaging' => 'messaging#index', :via => :post

  

end

app/models/reporter.rb
class Reporter < ActiveRecord::Base 
  validates_uniqueness_of :phone_number, :allow_blank => true
  validates_presence_of :first_name
  validates_presence_of :last_name

  attr_accessible :first_name
  attr_accessible :last_name
  attr_accessible :cast_ethnicity
  attr_accessible :sex
  attr_accessible :date_of_birth
  attr_accessible :address
  attr_accessible :phone_number

  has_many :conflict_cases
  USER_NAME, PASSWORD = 'iLab', '1c4989610bce6c4879c01bb65a45ad43'

  def full_name
    "#{first_name} #{last_name}"
  end

  def create_to_resource_map
    request = Typhoeus::Request.new(
      ResourceMapConfig["url"] + 'api/collections/' + ResourceMapConfig["collection_id"].to_s + '/register_new_member',
      method: :post,
      userpwd: "#{USER_NAME}:#{PASSWORD}",
      params: { "user[email]" => "", 
                "user[password]" => "", 
                "user[phone_number]" => self.phone_number
              },
      headers: { Accept: "text/html" }
    )
    request.run
    response = request.response.code
    return response == 200
  end

  def update_to_resourcemap reporter
    request = Typhoeus::Request.new(
      ResourceMapConfig["url"] + 'api/collections/' + ResourceMapConfig["collection_id"].to_s + '/memberships',
      method: :put,
      userpwd: "#{USER_NAME}:#{PASSWORD}",
      params: { "user[phone_number]" => reporter["phone_number"],
                "role" => "reporter",
                "reporter_phone" => self.phone_number
              },
      headers: { Accept: "text/html" }
    )
    request.run
    response = request.response.code
    return response == 200
  end

  def never_sent_case
    ConflictCase.find_by_reporter_id(self.id) == nil
  end

  def destroy_from_resource_map
    request = Typhoeus::Request.new(
      ResourceMapConfig["url"] + 'api/collections/' + ResourceMapConfig["collection_id"].to_s + '/destroy_member',
      method: :delete,
      userpwd: "#{USER_NAME}:#{PASSWORD}",
      params: { 
                "user[phone_number]" => self.phone_number
              },
      headers: { Accept: "text/html" }
    )
    request.run
    response = request.response.code
    return response == 200
  end

end

app/controllers/reporters_controller.rb
class ReportersController < ApplicationController  
  before_filter :authenticate_user!

  def index  
    @fields = ConflictCase.get_fields
    if params[:query]
      @query = params[:query]
      @reporters = Reporter.where('last_name like ? OR first_name like ? OR phone_number like ?',"%#{@query}%","%#{@query}%","%#{@query}%").order(:first_name).paginate(:page => params[:page], :per_page => 3)
    else
      @reporters = Reporter.all.order(:first_name).paginate(:page => params[:reporter_page], :per_page => PageSize)
    end
  end

  def show
  	
  end

  def new
  	@reporter = Reporter.new()
  end

  def create
    @reporter = Reporter.new(params[:reporter])
    @reporter.date_of_birth = DateTime.strptime(params["reporter"]["date_of_birth"], "%m-%d-%Y") unless params["reporter"]["date_of_birth"].strip.empty?
    if @reporter.create_to_resource_map
    	if @reporter.save
        flash[:notice] = "You have successfully created reporter #{@reporter.first_name} #{@reporter.last_name}."
        redirect_to reporters_path
      else
        render :new
      end
    else
      flash[:error] = "Failed to create reporter on resource map application. Please try again later."
      render :new
    end
  end

  def test

  end

  def edit
    @reporter = Reporter.find(params[:id])
    @reporter.date_of_birth = @reporter.date_of_birth.strftime("%m-%d-%Y") if @reporter.date_of_birth
  end

  def getReporterCasesPagination
    @fields = ConflictCase.get_fields
    json_data = {}
    table_rows = ""
    site_ids = []
    page_size = 10
    cases = ConflictCase.all.where(:reporter_id => params[:id]).offset(params[:offset].to_i).limit(page_size)
    unless cases.empty?
      cases.each do |c|
        site_ids.push(c.site_id)
      end
      sites = ConflictCase.get_some_sites_from_resourcemap(site_ids)
      @reporter_cases = ConflictCase.transform(sites, @fields)
    else
      @reporter_cases = []
    end

    @reporter_cases.count == 0 ? table_rows = "<tr><td colspan='5' style='text-align: center; color: red; padding-top: 20px;'>No records found</td></tr>" : table_row = ""
    @reporter_cases.each do |el|
      location = Location.find_by_id(el.location_id)
      row = "<tr><td style='width: 200px;'>#{el.created_at.in_time_zone(TimeZone).strftime("%m-%d-%Y %H:%M:%S")}</td>"
      @fields.each do |f|
        row += "<td>#{el.get_properties_value("label", f)}</td>"
      end
      row += "<td>#{location.name}</td></tr>"  
      table_rows = table_rows + row
    end
    json_data["table_row"] = table_rows
    
    if @reporter_cases.count >= page_size
      if (params[:offset].to_i <= 0)
        params[:offset] = 0
        paging = "<div class='pagination' id='paginate_report'><ul>"
        paging += "<li class='active'><a>Prev</a></li>"
        paging += "<li><a style='cursor: pointer;' onclick='updateModalPaging(#{params[:id]},#{params[:offset]} + #{page_size})'>Next</a></li>"
        paging += "</ul> </div>"
      elsif (ConflictCase.where(:reporter_id => params[:id]).count - page_size) - params[:offset].to_i == 0
        paging = "<div class='pagination' id='paginate_report'><ul>"
        paging += "<li><a style='cursor: pointer;' onclick='updateModalPaging(#{params[:id]},#{params[:offset]} - #{page_size})'>Prev</a></li>"
        paging += "<li class='active'><a>Next</a></li>"
        paging += "</ul> </div>"
      else 
        paging = "<div class='pagination' id='paginate_report'><ul>"
        paging += "<li><a style='cursor: pointer;' onclick='updateModalPaging(#{params[:id]},#{params[:offset]} - #{page_size})'>Prev</a></li>"
        paging += "<li><a style='cursor: pointer;' onclick='updateModalPaging(#{params[:id]},#{params[:offset]} + #{page_size})'>Next</a></li>"
        paging += "</ul> </div>"
      end
    else
      if (@reporter_cases.count - page_size) < params[:offset].to_i && params[:offset].to_i > 0
        paging = "<div class='pagination' id='paginate_report'><ul>"
        paging += "<li><a style='cursor: pointer;' onclick='updateModalPaging(#{params[:id]},#{params[:offset]} - #{page_size})'>Prev</a></li>"
        paging += "<li class='active'><a>Next</a></li>"
        paging += "</ul> </div>"
      end
    end
    json_data["paging"] = paging
    render :json => json_data
  end

  def update
    @reporter = Reporter.find(params[:id])
    if @reporter.update_to_resourcemap params[:reporter]
      if(@reporter.update_attributes(params[:reporter]))
        @reporter.date_of_birth = DateTime.strptime(params["reporter"]["date_of_birth"], "%m-%d-%Y")  unless params["reporter"]["date_of_birth"].strip.empty?
        @reporter.save
        flash[:notice] = "You have successfully updated reporter #{@reporter.first_name} #{@reporter.last_name}."
        redirect_to reporters_path
      else
        render :edit
      end
    else
      flash[:error] = "Failed to update reporter on resource map application. Please try again later."
      render :edit
    end
  end

  def destroy
    @reporter= Reporter.find(params[:id])
    if @reporter.never_sent_case
      if @reporter.destroy_from_resource_map
        if @reporter.destroy
          flash[:notice] = "You have successfully deleted reporter #{@reporter.first_name} #{@reporter.last_name}."
          redirect_to reporters_path
        else
          flash[:error] = "Failed to delete reporter #{@reporter.first_name} #{@reporter.last_name}. Please try again later."
          redirect_to reporters_path
        end
      else
        flash[:error] = "Failed to delete reporter #{@reporter.first_name} #{@reporter.last_name} from Resource map application."
        redirect_to reporters_path
      end
    else
      flash[:error] = "Failed to delete reporter #{@reporter.first_name} #{@reporter.last_name}. This reporter has sent some cases to the system."
      redirect_to reporters_path
    end
  end

  def export_csv
    header = "First Name, Last Name, Gender, Caste/Ethnicity, Address, Phone Number"
    items = header + "\n"
    Reporter.all.each do |reporter|
      item = []
      item.push(reporter.first_name)
      item.push(reporter.last_name)
      item.push(reporter.sex)
      item.push(reporter.cast_ethnicity)
      item.push(reporter.address)
      item.push(reporter.phone_number)
      items = items + item.join(",") + "\n"
    end
    send_data items,
      :type => 'text/csv; charset=utf-8; header=present',
      :filename => "reporters.csv"
  end
end

app/views/reporters/_form.html.erb
<% if reporter.errors.any? %>
    <div class="alert alert-block">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <div id="error_explanation">
            <h4><%= pluralize(reporter.errors.count, "error") %> prohibited this post from being saved:</h4>

            <ul>
            <% reporter.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    </div>
<% end %>
<%= form_for(reporter, :url => {:action => action} , :html => {:class => 'form-horizontal'} ) do |f| %>    
    <fieldset>                
        <!-- Name -->
        <div class="control-group">
            <%= f.label "First Name",:class => "control-label" %>
            <div class="controls">
                <%= f.text_field :first_name, :class =>"input-xlarge", :required => "required" %>
            </div>
        </div>

        <div class="control-group">
            <%= f.label "Last Name",:class => "control-label" %>
            <div class="controls">
                <%= f.text_field :last_name, :class =>"input-xlarge", :required => "required" %>
            </div>
        </div>

        <div class="control-group">
            <%= f.label "Gender",:class => "control-label" %>
            <div class="controls">
                <%= f.select(:sex, options_for_select(["Male", "Female"].collect {|p| [p] }, f.object.sex)) %>
            </div>
        </div>
        
        <div class="control-group">
            <%= f.label "Date of birth",:class => "control-label" %>
            <div class="controls">
                <%= f.text_field :date_of_birth, :class =>"datepicker"%>
                
            </div>
        </div>        

        <div class="control-group">
            <%= f.label "Caste/Ethnicity",:class => "control-label" %>
            <div class="controls">
                <%= f.text_field :cast_ethnicity, :class =>"input-xlarge"%>
            </div>
        </div>

        <div class="control-group">
            <%= f.label "Phone Number",:class => "control-label" %>
            <div class="controls">
                <%= f.text_field :phone_number, :class =>"input-xlarge", :required => "required" %>
            </div>
        </div>

        <div class="control-group">
            <%= f.label "Address",:class => "control-label" %>
            <div class="controls">
                <%= f.text_area :address, :class =>"input-xlarge" %>
            </div>
        </div>
        
        <!-- Submit -->
        <div class="control-group">
            <div class="controls">
                <button class="btn btn-success">Save</button>
                <%=link_to "Cancel", reporters_path, :class => "btn" %>
            </div>
        </div>
    </fieldset>
<% end %>
<script>
    $('.datepicker').datepicker({format: 'mm-dd-yyyy'})
</script>

app/views/reporters/edit.html.erb
    <div class="row-fluid">
        <div id="legend">
            <legend class="">Edit Reporter - <%= @reporter.first_name %> <%= @reporter.last_name %></legend>
        </div>
        <%= render "form", {:reporter => @reporter, :action => "update"} %>
    </div>

app/views/reporters/index.html.erb
<div class="btn-toolbar">
	<form class="form-search input-append" action=<%= reporters_path() %>>
	    <div class="input-append" method="#">
	    	<input type="text" class="span4 search-query" placeholder="Search First name, Last name, Phone number ..." id="query" name="query" value=<%= @query %>>
	    	<button type="submit" class="btn">Search</button>
	    </div>
	</form>
	<%= link_to "Add New Reporter", new_reporter_path, :method => :get, :class => 'btn btn-primary to-right' %>	
	<a class="btn dropdown-toggle to-right" href="<%= export_csv_reporters_path()%>" style="margin-right:20px;">
		<i class="icon-download"></i> Export to excel</span>
	</a>    
</div>
<div>
	<!--<table class="table table-bordered table-striped">-->
    <table class="table table-condensed table-hover">
	    <thead>
		    <tr>
			    <th>First Name</th>
			    <th>Last Name</th>
			    <th>Gender</th>
			    <th>Caste/Ethnicity</th>
			    <th>Address</th>
			    <th>Phone Number</th>
			    <th style="width: 36px;"></th>
		    </tr>
	    </thead>
	    <tbody>
		    <% @reporters.each do |reporter| %>			    
			    <tr>
				    <td><%= reporter.first_name %></td>
				    <td><%= reporter.last_name %></td>
				    <td><%= reporter.sex %></td>
				    <td><%= reporter.cast_ethnicity %></td>
				    <td><%= reporter.address %></td>
				    <td><%= reporter.phone_number %></td>
				    <td style="width: 145px;">
				    	<a class="" data-toggle="modal" href="#betaModal" onclick="updateModalPaging(<%= reporter.id %>, 0);">View Case Reported</a> 
			    	</td>
				    <td>
				    <%= link_to raw("<i class='icon-pencil'></i>"), edit_reporter_path(reporter), :method => :get %>
				    <%= link_to raw("<i class='icon-remove'></i>"), reporter_path(reporter), :method => :delete, :confirm => "Are you sure to delete reporter #{reporter.first_name} #{reporter.last_name}?" %>
				    </td>

			    </tr>
			<% end %>
		</tbody>
    </table>
</div>
<div>
	<span class="badge" style="padding:5px;margin-right:5px;">Display record : <%= @reporters.size %> / <%= @reporters.total_entries %>
	</span>
</div>
<%= will_paginate @reporters, :param_name => 'reporter_page', renderer: BootstrapPagination::Rails %>
<div id="betaModal" class="modal hide fade" style="width:1000px; margin-left:-500px">
    <div class="modal-header">
            <button class="close" data-dismiss="modal">×</button>
            <h3> Case Reported </h3>
    </div>
	<div class="modal-body" id="reporter_case">
	    <div>
	    	<!--<table class="table table-bordered table-striped">-->
		    <table class="table table-condensed table-hover" id="mytable">
			    <thead>
				    <tr>
					    <th>Reported date</th>
					    <% @fields.each do |f| %>	
					    	<th><%= f["name"] %></th>
						<% end %>
					    <th>Location</th>
				    </tr>
			    </thead>
			    <tbody>
				</tbody>
		    </table>
	    </div>
	</div>
	<div class="modal-footer">
		<a href="#" data-dismiss="modal" class="btn btn-primary">Close</a>
	</div>
</div>
<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Delete Confirmation</h3>
	</div>
	<div class="modal-body">
	    <p class="error-text">Are you sure you want to delete the user?</p>
	</div>
	<div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
	    <button class="btn btn-danger" data-dismiss="modal">Delete</button>
    </div>	    
</div>

app/views/reporters/new.html.erb
<div class="row-fluid">
    <div id="legend">
        <legend class="">New Reporter</legend>
    </div>
    <%= render "form", {:reporter => @reporter, :action => "create" } %>
</div>