config/routes.rb
Conflict::Application.routes.draw do
  devise_for :users,
    controllers: {
    registrations:  "users/registrations",
    passwords:      "users/passwords",
  }

  root 'home#index'

  resources :locations do 
    collection do
      get 'import'
      post 'import_process'
      get 'download_location_template'
    end

    member do
      get 'cancel_delete'
      get 'cancel_update'
      get 'approve_delete'
      get 'approve_update'
      get 'view_difference'
      put 'apply_update_form'
    end
  end
  resources :reporters do
    collection do
      get 'getReporterCasesPagination'
      get 'export_csv'
    end
  end

  resources :alerts
  resources :settings

  resources :trends do
    collection do
      get 'fetchCaseForGraph'
      get 'download_csv'
    end
  end

  resources :messages

  resources :conflict_cases do
    collection do
      get 'get_field_options'
      get 'get_indicator_options'
      get 'export_as_kml'
      get 'export_as_shp'
      get 'failed_messages'
    end
    member do
      get 'cancel_delete'
      get 'cancel_update'
      get 'approve_delete'
      get 'approve_update'
      get 'view_difference'
      put 'apply_update_form'
    end
  end
  resources :users do
    collection do
      post 'register'

    end

    member do
      put 'update_password'
      get 'change_password'
    end
  end

  match 'messaging' => 'messaging#index', :via => :post

  

end

app/models/location.rb
class Location < ActiveRecord::Base    
  validates_uniqueness_of :code, :allow_blank => true
  validates_presence_of :name
  validates_presence_of :lat
  validates_presence_of :lng
  validates_presence_of :code
  validates_numericality_of :lat, :greater_than_or_equal_to => -90, :less_than_or_equal_to => 90 ,:message => "must be less than 90 and larger than -90"
  validates_numericality_of :lng, :greater_than_or_equal_to => -180, :less_than_or_equal_to => 180, :message => "must be less than 180 and larger than -180"

  
  attr_accessible :name
  attr_accessible :lat
  attr_accessible :lng
  attr_accessible :code
  attr_accessible :is_deleted
  attr_accessible :is_updated
  USER_NAME, PASSWORD = 'iLab', '1c4989610bce6c4879c01bb65a45ad43'

  def lnglat
    "#{lng},#{lat}"
  end

  def description
    name + "(" + code + ")"
  end

  def update_to_resourcemap site_ids, user_emails
    request = Typhoeus::Request.new(
      ResourceMapConfig["url"] + "api/collections/" + ResourceMapConfig["collection_id"].to_s + "/update_sites",
      userpwd: "#{USER_NAME}:#{PASSWORD}",
      method: :put,
      body: "this is a request body",
      params: { lat: self.backup.data["lat"], lng: self.backup.data["lng"], site_id: site_ids, user_email: user_emails },
      headers: { Accept: "text/html" }
    )
    request.run
    response = request.response.code
    return response == 200
	end

  def self.update_latlng_to_resourcemap site_ids, user_emails, new_lat, new_lng
    request = Typhoeus::Request.new(
      ResourceMapConfig["url"] + "api/collections/" + ResourceMapConfig["collection_id"].to_s + "/update_sites",
      userpwd: "#{USER_NAME}:#{PASSWORD}",
      method: :put,
      body: "this is a request body",
      params: { lat: new_lat, lng: new_lng, site_id: site_ids, user_email: user_emails },
      headers: { Accept: "text/html" }
    )
    request.run
    response = request.response.code
    return response == 200
  end

  def self.generate_site_id conflict_cases
    array_site = []
    conflict_cases.each do |el|
      array_site << el.site_id
    end
    site_ids = array_site.join(",")
    return site_ids
  end 

  def self.generate_user_email conflict_cases
    array_email = []
    conflict_cases.each do |el|
      array_email << User.find_by_id(el.user_id).email
    end
    user_emails = array_email.join(",")
    return user_emails
	end

  def self.get_category
    'location'
  end

  def backup
    backup = Backup.find_by_entity_id_and_category(self.id, Location.get_category)
    backup.data = JSON.parse backup.data if backup
    backup
  end

  def never_present_in_conflict
    ConflictCase.find_by_location_id(self.id) == nil
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController  
  before_filter :authenticate_user!

  def index
    @locations = Location.all.paginate(:page => params[:page], :per_page => PageSize)
  end

  def show
  	
  end

  def new
  	@location = Location.new()
  end

  def create
    @location = Location.new(params[:location])
  	if @location.save
      flash[:notice] = "You have successfully created location #{@location.name}."      
      redirect_to locations_path
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
    if(@location.is_updated)
      flash[:error] = "Location #{@location.name} is marked as updated. Please approve the update before make another change."
      redirect_to locations_path
    end
    if(@location.is_deleted)
      flash[:error] = "Location #{@location.name} is marked as deleted. Please cancel delete before make another change."
      redirect_to locations_path
    end

  end

  def update
    @location = Location.find(params[:id])
    if @location.is_updated       
      unless @location.backup.user.id == current_user.id
        flash[:error] = "Location #{@location.name} is marked as updated please click Approve to update to confirm update location."
        redirect_to locations_path
      else
        flash[:error] = "Failed to update location #{@location.name}. Please try again later."
        redirect_to locations_path
      end

    else
      flash[:notice] = "#{@location.name} is marked as updated."
      Backup.create!(:entity_id => @location.id, :data => params[:location].to_json, :category => Location.get_category, :user_id => current_user.id)
      @location.is_updated = true
      @location.save
      redirect_to locations_path
    end
    
    
  end

  def destroy
    @location = Location.find(params[:id])
    if @location.never_present_in_conflict
      if @location.is_deleted 
        unless @location.backup.user.id == current_user.id
          flash[:error] = "Location #{@location.name} is marked as deleted please click Approve to delete to confirm delete location."
          redirect_to locations_path
        else
          flash[:error] = "Failed to delete location #{@location.name}. Please try again later."
          redirect_to locations_path
        end
      else
        flash[:notice] = "#{@location.name} is marked as deleted."
        Backup.create!(:entity_id => @location.id, :data => @location.to_json, :category => Location.get_category, :user_id => current_user.id)
        @location.is_deleted = true
        @location.save
        redirect_to locations_path
      end
    else
      flash[:error] = "Failed to delete location #{@location.name}. This location has been reported in case."
      redirect_to locations_path
    end
  end

  def import
    
  end

  def import_process
    max_file_size = 1024000 
    datas = {}
    errors = {}
    redundant_list = []
    if(params["location"]["file_import"])
      file_obj = params["location"]["file_import"]
      file_size = File.size(file_obj.path)
      errors = { "data" => file_size, "error_type" => "File over limited size. Currently we allow only 1MB file size." } if file_size > max_file_size
      filename = file_obj.original_filename
      if(errors.empty? and !filename.end_with? ".csv")
        errors = { "data" =>filename ,"error_type" => "File is not csv format." }  
      end

      if(errors.empty? and !Import::validate_header?(file_obj.path))
        error_type = Import::get_error_type
        errors = { "data" =>filename ,"error_type" => error_type}
      end 

      if(errors.empty?)
        @rows = Import::process_import file_obj.path, params[:allow_to_override], current_user
        msg = "You have successfully imported #{@rows[:success]} locations to your system with #{@rows[:failed]} failed and #{@rows[:updated]} updated on existed location."
        flash[:notice] = msg
        @locations = Location.all.paginate(:page => params[:page], :per_page => 10)
        redirect_to locations_path
      else
        flash[:error] = "Process import failed. #{errors['error_type']}"
        render :import
      end
    end
  end

  def download_location_template
    respond_to do |format|
      format.json  { render :json => result }
      format.csv {
        content = "name,code,lat,lng"
        render :text => content
      }
    end
  end

  def cancel_delete
    @location = Location.find(params[:id])
    if(@location.is_deleted and @location.backup)
      flash[:notice] = "#{@location.name} is marked as undeleted."
      @location.backup.destroy
      @location.is_deleted = false
      @location.save
      redirect_to locations_path
    else
      redirect_to locations_path
    end
  end

  def cancel_update
    @location = Location.find(params[:id])
    if(@location.is_updated and @location.backup)
      flash[:notice] = "#{@location.name} is marked as not updated."
      @location.backup.destroy
      @location.is_updated = false
      @location.save
      redirect_to locations_path
    else
      redirect_to locations_path
    end
  end

  def approve_delete
    @location = Location.find(params[:id])
    if(@location and @location.is_deleted and @location.backup and @location.backup.user.id != current_user.id)
      @location.destroy!
      @location.backup.destroy!
      flash[:notice] = "You have successfully deleted #{@location.name}."
      redirect_to locations_path
    else
      flash[:error] = "Process delete #{@location.name} failed."
      redirect_to locations_path
    end
  end

  def approve_update
    @location = Location.find(params[:id])
    if(@location and @location.is_updated and @location.backup and @location.backup.user.id != current_user.id)
      conflict_cases = ConflictCase.where(:location_id => params[:id])
      site_ids = Location.generate_site_id conflict_cases
      user_emails = Location.generate_user_email conflict_cases
      if @location.update_to_resourcemap(site_ids, user_emails)
        if(@location.update_attributes!(@location.backup.data))        
          flash[:notice] = "You have successfully updated location #{@location.name}."
          @location.backup.destroy!
          @location.is_updated = false
          @location.save
          redirect_to locations_path
        else
          redirect_to locations_path
        end 
      else
        flash[:error] = "Failed to update location on resource map application. Please try again later."
        redirect_to locations_path
      end     
    else
      flash[:error] = "Process update #{@location.name} failed."
      redirect_to locations_path
    end
  end

  def apply_update_form
    @location = Location.find(params[:id])
    if(@location and @location.is_updated and @location.backup and @location.backup.user.id != current_user.id)
      conflict_cases = ConflictCase.where(:location_id => params[:id])
      site_ids = Location.generate_site_id conflict_cases
      user_emails = Location.generate_user_email conflict_cases
      if @location.update_to_resourcemap(site_ids, user_emails)
        if(@location.update_attributes!(params[:location]))        
          flash[:notice] = "You have successfully updated location #{@location.name}."
          @location.backup.destroy!
          @location.is_updated = false
          @location.save
          redirect_to locations_path
        else
          redirect_to locations_path
        end 
      else
        flash[:error] = "Failed to update location on resource map application. Please try again later."
        redirect_to locations_path
      end     
    else
      flash[:error] = "Process update #{@location.name} failed."
      redirect_to locations_path
    end
  end

  def view_difference
    @base = Location.find(params[:id])
  end
end

app/views/locations/_form.html.erb
<% if location.errors.any? %>
    <div class="alert alert-block">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <div id="error_explanation">
            <h4><%= pluralize(location.errors.count, "error") %> prohibited this post from being saved:</h4>
         
            <ul>
            <% location.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    </div>
<% end %>
<%= form_for(location, :url => {action: action} , :html => {:class => 'form-horizontal'} ) do |f| %>    
    <fieldset>                
        <div class="control-group">
            <%= f.label "Location Name",:class => "control-label" %>
            <div class="controls">
                <%= f.text_field :name, :class =>"input-xlarge", :required => "required" %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label "Location Code",:class => "control-label" %>
            <div class="controls">
                <%= f.text_field :code, :class =>"input-xlarge", :required => "required" %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label "Latitude",:class => "control-label" %>
            <div class="controls">
                <%= f.text_field :lat, :class =>"input-xlarge", :required => "required" %>
            </div>
        </div>

        <div class="control-group">
            <%= f.label "Longtitude",:class => "control-label" %>
            <div class="controls">
                <%= f.text_field :lng, :class =>"input-xlarge", :required => "required" %>
            </div>
        </div>
        
        <!-- Submit -->
        <div class="control-group">
            <div class="controls">
                <button class="btn btn-success">Save</button>
                <%=link_to "Cancel", locations_path, :class => "btn" %>
            </div>
        </div>
    </fieldset>
<% end %>

app/views/locations/_form_difference.html.erb
<% if is_super_admin? current_user %>
    <%= form_for(base, :url => apply_update_form_location_path(base) , :method => :put, :html => {:class => 'form-horizontal'} ) do |f| %>
        <div class="row-fluid">
            <div class="span6">
                <h4> Modified</h4>
                <fieldset>                
                    <div class="control-group">
                        <%= f.label "Location Name",:class => "control-label" %>
                        <div class="controls">
                            <input type="text" id="location_name" name="location[name]" required="required" class ="input-xlarge" value="<%= base.backup.data['name'] %>" />
                        </div>
                    </div>
                    <div class="control-group">
                        <%= f.label "Location Code",:class => "control-label" %>
                        <div class="controls">
                            <%= base.backup.data["Name"] %>
                            <input type="text" id="location_code" name="location[code]" required="required" class ="input-xlarge" value="<%= base.backup.data['code'] %>" />
                        </div>
                    </div>
                    <div class="control-group">
                        <%= f.label "Latitude",:class => "control-label" %>
                        <div class="controls">
                            <input type="text" id="location_lat" name="location[lat]" required="required" class ="input-xlarge" value="<%= base.backup.data['lat'] %>" />
                        </div>
                    </div>

                    <div class="control-group">
                        <%= f.label "Longtitude",:class => "control-label" %>
                        <div class="controls">
                            <input type="text" id="location_lng" name="location[lng]" required="required" class ="input-xlarge" value="<%= base.backup.data['lng'] %>" />
                        </div>
                    </div>
                    
                    <!-- Submit -->
                    <div class="control-group">
                        <div class="controls">
                            <button class="btn btn-success">Approve to update</button>
                            <%=link_to "Cancel", locations_path, :class => "btn" %>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="span6">
                <h4> Original</h4>
                <fieldset>                
                    <div class="control-group">
                        <%= f.label "Location Name",:class => "control-label" %>
                        <div class="controls">
                            <input type="text" readonly="readonly" class ="input-xlarge" value='<%= base.name %>' />
                        </div>
                    </div>
                    <div class="control-group">
                        <%= f.label "Location Code",:class => "control-label" %>
                        <div class="controls">
                            <input type="text" readonly="readonly" class ="input-xlarge" value='<%= base.code %>' />
                        </div>
                    </div>
                    <div class="control-group">
                        <%= f.label "Latitude",:class => "control-label" %>
                        <div class="controls">
                            <input type="text" readonly="readonly" class ="input-xlarge" value='<%= base.lat %>' />
                        </div>
                    </div>

                    <div class="control-group">
                        <%= f.label "Longtitude",:class => "control-label" %>
                        <div class="controls">
                            <input type="text" readonly="readonly" class ="input-xlarge" value='<%= base.lng %>' />
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    <% end %>
<% end %>

app/views/locations/edit.html.erb
<div class="row-fluid">
    <div id="legend">
        <legend class="">Edit Place - <%= @location.name %></legend>
    </div>
    <%= render "form", {:location => @location, :action => "update" } %>
</div>

app/views/locations/import.html.erb
<div class="row-fluid">
    <div id="legend">                    
        <legend class="">Import Location</legend>
    </div>
    <div class="alert alert-info">
        This tool allows you to import a bunch of locations to your system by using a <%= link_to raw("location form"), download_location_template_locations_path + ".csv", :method => :get, :class => 'bold_link', :format => :csv %> as a template.
    </div>
    <%= form_for(:location, :url => "import_process" , :method => :post, :html => {:class => 'form-horizontal'} ) do |f| %>    
        <div class="control-group">
            <%= f.label "File",:class => "control-label" %>
            <div class="controls">
                <%= f.file_field :file_import, :class =>"input-xlarge", :required => "required" %>
            </div>
        </div>
        <div class="list-item">
            <%= f.label " ",:class => "control-label" %>
            <div class="controls">
                <span class="input-group-addon">
                    <input type="checkbox" value="1" name="allow_to_override"/>
                </span>
                <span class="email-label">
                    Allows to override existing location
                </span>  
            </div>
        </div> 
        <br />
        <div class="control-group">
            <div class="controls">
                <button class="btn btn-success">Upload</button>
                <%=link_to "Cancel", locations_path, :class => "btn" %>
            </div>
        </div>
    <% end %>
</div>

app/views/locations/index.html.erb
<div class="btn-toolbar">
	<%= link_to raw("<i class='icon-upload'></i> Import Location Code"), import_locations_path, :method => :get, :class => 'btn' %>
	<%= link_to "Add New Place", new_location_path, :method => :get, :class => 'btn btn-primary to-right' %>    
</div>
<% @is_updated = false %>
<% @is_deleted = false %>
<div>
	<!--<table class="table table-bordered table-striped">-->
    <table class="table table-condensed table-hover">
	    <thead>
		    <tr>
			    <th>Location Code</th>
			    <th>Location Name</th>
			    <th>Latitude</th>
			    <th>Longtitude</th>
			    <th style="width: 36px;"></th>
		    </tr>
	    </thead>
	    <tbody>
	    <% @locations.each do |l| %>
	    <% class_name = "" %>
	    <% if l.is_deleted %>
	    	<% class_name = "deleted" %>
	    <% elsif l.is_updated %>
	    	<% class_name = "updated" %>
	    <% end %>		    
		    <tr class=<%= class_name %>>
			    <td><%= l.code %></td>
			    <td><%= l.name %></td>
			    <td><%= l.lat %></td>
			    <td><%= l.lng %></td>
			    <td>
			    <% if l.is_deleted %>			
					<% @is_deleted = true %>	    	
			    	<div class="btn-group pull-right">
			    		<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
							<%= l.backup.user.first_name || "UNKNOWN" %> 
							<% if (l.backup.user.id != current_user.id and is_super_admin? current_user) or l.backup.user.id == current_user.id%>	
								<span class="caret"></span>
							<% end %>
						</a>
						
			    		<% if l.backup.user.id != current_user.id  and is_super_admin? current_user %>
			    			<ul class="dropdown-menu">
								<li><%= link_to " Approve to delete", approve_delete_location_path(l), :method => :get, :class => 'icon-ok-circle' %>
								<li class="divider"></li>
								<li><%= link_to " Cancel delete", cancel_delete_location_path(l), :method => :get, :class => 'icon-ban-circle' %></li>	
							</ul>							
						<% elsif l.backup.user.id == current_user.id %>
							<ul class="dropdown-menu">
								<li><%= link_to " Cancel delete", cancel_delete_location_path(l), :method => :get, :class => 'icon-ban-circle' %></li>
							</ul>
						<% end %>
						</ul>
					</div>						
			    <% elsif l.is_updated %>
			    	<% @is_updated = true %>
			    	<div class="btn-group pull-right">
						<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
							<%= l.backup.user.first_name || "UNKNOWN" %>
							<% if (l.backup.user.id != current_user.id and is_super_admin? current_user) or l.backup.user.id == current_user.id%>	
									<span class="caret"></span>
							<% end %>
						</a>
						<% if l.backup.user.id != current_user.id  and is_super_admin? current_user%>
							<ul class="dropdown-menu">							
								<li><%= link_to " View the difference", view_difference_location_path(l), :method => :get, :class => 'icon-eye-open' %>
								<li class="divider"></li>
								<li><%= link_to " Approve to update", approve_update_location_path(l), :method => :get, :class => 'icon-ok-circle' %>
								<li class="divider"></li>
								<li><%= link_to " Cancel update", cancel_update_location_path(l), :method => :get, :class => 'icon-ban-circle' %></li>	
							</ul>	
						<% elsif l.backup.user.id == current_user.id %>
							<ul class="dropdown-menu">
								<li><%= link_to " Cancel update", cancel_update_location_path(l), :method => :get, :class => 'icon-ban-circle' %></li>
							</ul>
						<% end %>
					</div>
			    <% else %>						
				    <%= link_to raw("<i class='icon-pencil'></i>"), edit_location_path(l), :method => :get %>
				    <%= link_to raw("<i class='icon-remove'></i>"), location_path(l), :method => :delete, :confirm => "Are you sure to delete location #{l.code}?" %>
			    <% end %>
			    </td>
		    </tr>
		<% end %>
		</tbody>
    </table>
</div>
<% if @is_deleted %>
	<div class="row-fluid"  style="margin:5px">
		<div class="span1 img-rounded deleted_ex">
	    	&nbsp;
	    </div>
	    <div class="span4" style="padding-top:5px">
	        Record is marked as Deleted
	    </div>
	</div>
<% end %>
<% if @is_updated %>
	<div class="row-fluid"  style="margin:5px">
		<div class="span1 img-rounded updated_ex">
	    	&nbsp;
	    </div>
	    <div class="span4" style="padding-top:5px">
	        Record is marked as Updated
	    </div>
	</div>
<% end %>
<div id="errorModal" class="modal hide fade" style="width:760px; margin-left:-380px">
    <div class="modal-header">
            <button class="close" data-dismiss="modal">×</button>
            <h3> Error Location Record </h3>
    </div>
	<div class="modal-body" id="reporter_case">
	    <div>
	    	<!--<table class="table table-bordered table-striped">-->
		    <table class="table table-condensed table-hover" id="mytable">
			    <thead>
				    <tr>
					    <th>Location Name</th>
					    <th>Location Code</th>
					    <th>Latitude</th>
					    <th>Longtitude</th>
					    <th>Status</th>
				    </tr>
			    </thead>
			    <tbody>
			    <% if @rows and @rows[:error_records] %>
			    	<% @rows[:error_records].each do |r| %>
			    		<tr>
			    			<td><%= r["name"] %></td>
			    			<td><%= r["code"] %></td>
			    			<td><%= r["lat"] %></td>
			    			<td><%= r["lng"] %></td>
			    			<td><%= r["error_messages"] %></td>
			    		</tr>
			    	<% end %>
			    <% end %>
				</tbody>
		    </table>
	    </div>	    
	</div>
	<div class="modal-footer">
		<a href="#" data-dismiss="modal" class="btn btn-primary">Close</a>
	</div>
</div>
<div>
	<span class="badge" style="padding:5px;margin-right:5px;">Display record : <%= @locations.size %> / <%= @locations.total_entries %>
	</span>
</div>
<%= will_paginate @locations, renderer: BootstrapPagination::Rails %>
<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Delete Confirmation</h3>
	</div>
	<div class="modal-body">
	    <p class="error-text">Are you sure you want to delete the user?</p>
	</div>
	<div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
	    <button class="btn btn-danger" data-dismiss="modal">Delete</button>
    </div>
</div>

<% if @rows and !@rows[:error_records].empty? %>
	<script type="text/javascript">
		  $('#errorModal').modal('show');
	</script>
<% end %>

app/views/locations/new.html.erb
<div class="row-fluid">
    <div id="legend">                    
        <legend class="">New Place</legend>
    </div>
    <!-- Name -->
    <%= render "form", {:location => @location, :action => "create" } %>
</div>

app/views/locations/show.html.erb
<h3>Show</h3>

app/views/locations/view_difference.html.erb
<div class="row-fluid">
    <div id="legend">                    
        <legend class="">View Difference</legend>
    </div>
    <!-- Name -->
    <%= render "form_difference", {:base => @base} %>
</div>