config/routes.rb
Conflict::Application.routes.draw do
  devise_for :users,
    controllers: {
    registrations:  "users/registrations",
    passwords:      "users/passwords",
  }

  root 'home#index'

  resources :locations do 
    collection do
      get 'import'
      post 'import_process'
      get 'download_location_template'
    end

    member do
      get 'cancel_delete'
      get 'cancel_update'
      get 'approve_delete'
      get 'approve_update'
      get 'view_difference'
      put 'apply_update_form'
    end
  end
  resources :reporters do
    collection do
      get 'getReporterCasesPagination'
      get 'export_csv'
    end
  end

  resources :alerts
  resources :settings

  resources :trends do
    collection do
      get 'fetchCaseForGraph'
      get 'download_csv'
    end
  end

  resources :messages

  resources :conflict_cases do
    collection do
      get 'get_field_options'
      get 'get_indicator_options'
      get 'export_as_kml'
      get 'export_as_shp'
      get 'failed_messages'
    end
    member do
      get 'cancel_delete'
      get 'cancel_update'
      get 'approve_delete'
      get 'approve_update'
      get 'view_difference'
      put 'apply_update_form'
    end
  end
  resources :users do
    collection do
      post 'register'

    end

    member do
      put 'update_password'
      get 'change_password'
    end
  end

  match 'messaging' => 'messaging#index', :via => :post

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  	<title>SMS Violence Reporting System</title>
	  	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  	<%= stylesheet_link_tag    "datepicker", media: "all", "data-turbolinks-track" => true %>
	  	<%= javascript_include_tag "bootstrap-datepicker", "data-turbolinks-track" => true %>
	  	<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="navbar">
			<div class="navbar-inner">
				<div class="hearder_narrow">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						</a>
					<a class="brand" href="/" name="top">Sajhedari Bikaas</a>
					<div class="nav-collapse collapse">
						<ul class="nav">
							<li><%= link_to raw('<i class="icon-globe"></i> Map'), @rm["url"] + "collections" , :method => :get, :style => "padding: 10px" %></li>
							<li class="divider-vertical"></li>
							<li class=<%= section_active("reporters")  %>><%= link_to raw('<i class="icon-group"></i> Reporters'), reporters_path, :method => :get, :style => "padding: 10px" %></li>
							<li class="divider-vertical"></li>
							<li class=<%= section_active("trends")  %>><%= link_to raw('<i class="icon-signal"></i> Trend'), trends_path, :method => :get, :style => "padding: 10px" %></li>
							<li class="divider-vertical"></li>
							<% if current_user.role.name == "Super Admin" %>
								<li class="dropdown <%= section_active("alerts")  %> ">
									<a class="dropdown-toggle" href="#" data-toggle="dropdown">
										<i class="icon-warning-sign"></i> Alert <strong class="caret"></strong>
									</a>
									<ul class="dropdown-menu">									
											<li><%= link_to raw('<i class="icon-bell"></i> Case Based Alert'), @rm["url"] + "plugin/alerts/collections/" + @rm["collection_id"].to_s + "/thresholds" , :method => :get, :style => "padding: 10px"%></li>										
											<li class=<%= section_active("alerts")  %>><%= link_to raw('<i class="icon-warning-sign"></i> Aggregate Threshold Alert'), alerts_path, :method => :get, :style => "padding: 10px" %>
									</ul>
								</li>
							<% else %>
								<li class=<%= section_active("alerts")  %>><%= link_to raw('<i class="icon-warning-sign"></i> Aggregate Threshold Alert'), alerts_path, :method => :get, :style => "padding: 10px" %>
							<% end %>
							<li class="divider-vertical"></li>
							<li class=<%= section_active("conflict_cases")  %>><%= link_to raw('<i class="icon-comment"></i> Cases Reported'), conflict_cases_path, :method => :get, :style => "padding: 10px" %></li>
						<!--	<li class=<%= section_active("alerts")  %>><%= link_to raw('<i class="icon-warning-sign"></i> Aggregate Threshold Alert'), alerts_path, :method => :get, :style => "padding: 10px" %> </li> -->
							<li class="divider-vertical"></li>
							<li class=<%= section_active("locations")  %>><%= link_to raw('<i class="icon-map-marker"></i> Locations'), locations_path, :method => :get, :style => "padding: 10px" %></li>
							<li class="divider-vertical"></li>
							<li class=<%= section_active("users")  %>><%= link_to raw('<i class="icon-user"></i> Users'), users_path, :method => :get, :style => "padding: 10px" %></li>
							<li class="divider-vertical"></li>
							<li class=<%= section_active("settings")  %>><%= link_to raw('<i class="icon-cog"></i> Settings'), settings_path, :method => :get, :style => "padding: 10px" %></li>
							<li class="divider-vertical"></li>
						</ul>
						
						<div class="btn-group pull-right">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="icon-user"></i> <%= current_user.first_name || "UNKNOWN" %> <span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to " Profile", edit_user_path(current_user), :method => :get, :class => 'icon-user' %>
								<li class="divider"></li>
								<li><%= link_to " Change Password", change_password_user_path(current_user), :method => :get, :class => 'icon-cog' %>
								<li class="divider"></li>
								<li><%= link_to " Sign out", destroy_user_session_path, :method => :delete, :class => 'icon-share' %></li>
							</ul>
						</div>
					</div>
				<!--/.nav-collapse -->
				</div>
			<!--/.container-fluid -->
			</div>
		<!--/.navbar-inner -->
		</div>
		<div class="span2" style="text-align:right;">
			<img src="/usaid.jpg" alt="USAID" />
			<br />
			<br />
			<center>
				<h6 style="text-align:center;">
					<i><font color="red" size="6"> Conflict Mapping System </font></i>
				</h6>
			</center>
		</div>
		<div class="span10 body-content" style="min-width:1000px">
			<center>
				<% if flash[:error] -%>
				    <div class="alert alert-error">
					    <button type="button" class="close" data-dismiss="alert">&times;</button>
					    <%=h flash[:error] %>
				    </div>
				<% end -%>
				<% if flash[:notice] -%>
				  	<div class="alert alert-success">
					    <button type="button" class="close" data-dismiss="alert">&times;</button>
					    <%=h flash[:notice] %>
				    </div>
				<% end -%>
			</center>
			<%= yield %>
			<hr>
			<footer>
				<center>Sajhedari Bikaas Project(ref: AID-367-C-13-00003)</center>
			</footer>
		</div>
	</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>SMS Violence Reporting System</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body class="nepal">

		<div class="body-login-content">
			<div class="header">
				<div class="sponsor">
					&nbsp;
				</div>
				<div class="project_name" style="text-align:right;">
					<img src="/usaid.jpg" alt="USAID" />
					<div style="padding-right:10px">
						<div>
							<h4>
								<font color="red" size="bold"> Sajhedari Bikaas Project </font>
							</h4>
						</div>
						<div style="margin-top:-10px;">
							<i><font color="gray" size="1.5" style="padding-right:25px;"> Partnership for Local Development </font></i>
						</div>
					</div>
				</div>
				<div class="project_title">
					&nbsp;
				</div>
				

			</div>
			<div class="clear"></div>
			<div class="to_left">
				<%= yield %>
			</div>
			<hr>
			<footer>
				<center>Sajhedari Bikaas Project(ref: AID-367-C-13-00003)</center>
			</footer>
		</div>
	</body>
</html>